"""Persistence contracts for the generic-agent runtime."""

from __future__ import annotations

from typing import Protocol

from hello_sales_backend.platform.agents.models import (
    AgentArtifact,
    AgentDiagnosticsSummary,
    AgentRun,
    AgentStreamEvent,
    AgentToolCall,
    AgentTurn,
)


class AgentStorePort(Protocol):
    """Persistence contract for generic-agent operational state."""

    async def create_run(self, run: AgentRun) -> None: ...

    async def get_run(self, run_id: str) -> AgentRun | None: ...

    async def update_run(self, run: AgentRun) -> None: ...

    async def create_turn(self, turn: AgentTurn) -> None: ...

    async def get_turn(self, turn_id: str) -> AgentTurn | None: ...

    async def list_turns(self, run_id: str) -> list[AgentTurn]: ...

    async def update_turn(self, turn: AgentTurn) -> None: ...

    async def create_tool_call(self, tool_call: AgentToolCall) -> None: ...

    async def list_tool_calls(self, run_id: str, turn_id: str) -> list[AgentToolCall]: ...

    async def get_tool_call_by_approval_id(self, approval_id: str) -> AgentToolCall | None: ...

    async def update_tool_call(self, tool_call: AgentToolCall) -> None: ...

    async def create_artifact(self, artifact: AgentArtifact) -> None: ...

    async def append_event(self, event: AgentStreamEvent) -> None: ...

    async def list_events(self, run_id: str, limit: int = 100) -> list[AgentStreamEvent]: ...

    async def next_turn_sequence(self, run_id: str) -> int: ...

    async def next_tool_sequence(self, run_id: str, turn_id: str) -> int: ...

    async def next_event_sequence(self, run_id: str) -> int: ...

    async def summarize(self, limit: int = 10) -> AgentDiagnosticsSummary: ...
