apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    common:
      path_prefix: /loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      storage:
        s3:
          endpoint: minio:9000
          bucketnames: loki
          access_key_id: ${MINIO_ACCESS_KEY}
          secret_access_key: ${MINIO_SECRET_KEY}
          insecure: true
          s3forcepathstyle: true
    schema_config:
      configs:
        - from: 2026-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    limits_config:
      retention_period: 720h
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    compactor:
      working_directory: /loki/compactor
      retention_enabled: true
      delete_request_store: filesystem
    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/rules-temp
