receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: basic
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheus:
    endpoint: 0.0.0.0:8889

processors:
  batch: {}
  resource:
    attributes:
      - key: service.namespace
        value: hello-sales
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp/tempo, debug]
    logs:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [loki, debug]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]
