apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../
  - prod-secrets.template.yaml

patchesStrategicMerge:
  - prometheus-prod-patch.yaml
  - grafana-prod-patch.yaml
  - ingress-prod-patch.yaml
  - minio-prod-patch.yaml
