apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../
  - staging-secrets.template.yaml

patchesStrategicMerge:
  - prometheus-staging-patch.yaml
  - grafana-staging-patch.yaml
  - ingress-staging-patch.yaml
