apiVersion: v1
kind: Secret
metadata:
  name: observability-secrets
type: Opaque
stringData:
  grafana-admin-user: admin
  grafana-admin-password: replace-me-staging
  minio-root-user: replace-me-staging
  minio-root-password: replace-me-staging
  minio-access-key: replace-me-staging
  minio-secret-key: replace-me-staging
