"""add salesbook tables

Revision ID: 0007_add_salesbook_tables
Revises: 0006_agent_run_auth_context
Create Date: 2026-04-26

/Oliviercontribution — adds the salesbook module schema.
6 tables (client_contact_extensions, onboarding_progress, onboarding_responses,
pipeline_deals, engagement_logs, team_memberships); all FK to
company_profiles.profile_id. No new clients/auth/billing tables (reuses
company_profile + auth modules; billing deferred to v2).
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007_add_salesbook_tables'
down_revision = '0006_agent_run_auth_context'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesbook_client_contact_extensions',
    sa.Column('extension_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('primary_email', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=False),
    sa.Column('contact_role', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('company_size', sa.String(length=64), nullable=True),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('extension_id')
    )
    op.create_index(op.f('ix_salesbook_client_contact_extensions_primary_email'), 'salesbook_client_contact_extensions', ['primary_email'], unique=False)
    op.create_index(op.f('ix_salesbook_client_contact_extensions_profile_id'), 'salesbook_client_contact_extensions', ['profile_id'], unique=True)
    op.create_table('salesbook_onboarding_progress',
    sa.Column('progress_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('phase1_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('phase2_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('phase3_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('phase1_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase2_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase3_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_completion_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progress_id')
    )
    op.create_index(op.f('ix_salesbook_onboarding_progress_profile_id'), 'salesbook_onboarding_progress', ['profile_id'], unique=True)
    op.create_table('salesbook_onboarding_responses',
    sa.Column('response_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('question_key', sa.String(length=128), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('response_value', sa.Text(), nullable=True),
    sa.Column('response_type', sa.String(length=64), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('profile_id', 'question_key', name='uq_salesbook_response_profile_question')
    )
    op.create_index(op.f('ix_salesbook_onboarding_responses_profile_id'), 'salesbook_onboarding_responses', ['profile_id'], unique=False)
    op.create_index(op.f('ix_salesbook_onboarding_responses_question_key'), 'salesbook_onboarding_responses', ['question_key'], unique=False)
    op.create_table('salesbook_pipeline_deals',
    sa.Column('deal_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('lead_source', sa.String(length=128), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=False),
    sa.Column('assigned_agent', sa.String(length=128), nullable=True),
    sa.Column('deal_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deal_probability', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_index(op.f('ix_salesbook_pipeline_deals_profile_id'), 'salesbook_pipeline_deals', ['profile_id'], unique=False)
    op.create_table('salesbook_team_memberships',
    sa.Column('membership_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('role_level', sa.String(length=32), nullable=False),
    sa.Column('can_invite', sa.Boolean(), nullable=False),
    sa.Column('can_export', sa.Boolean(), nullable=False),
    sa.Column('can_edit_onboarding', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id')
    )
    op.create_index(op.f('ix_salesbook_team_memberships_profile_id'), 'salesbook_team_memberships', ['profile_id'], unique=False)
    op.create_index(op.f('ix_salesbook_team_memberships_user_email'), 'salesbook_team_memberships', ['user_email'], unique=False)
    op.create_table('salesbook_engagement_logs',
    sa.Column('log_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('deal_id', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('action_detail', sa.Text(), nullable=True),
    sa.Column('action_reason', sa.Text(), nullable=True),
    sa.Column('action_result', sa.Text(), nullable=True),
    sa.Column('next_step', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('process_version', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['salesbook_pipeline_deals.deal_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_salesbook_engagement_logs_deal_id'), 'salesbook_engagement_logs', ['deal_id'], unique=False)
    op.create_index(op.f('ix_salesbook_engagement_logs_profile_id'), 'salesbook_engagement_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_salesbook_engagement_logs_timestamp'), 'salesbook_engagement_logs', ['timestamp'], unique=False)
    # NOTE: Alembic autogenerate suggested dropping uq_session_summaries_session_id —
    # that's a SQLite-vs-Postgres autogenerate false positive. Removed by /Oliviercontribution.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (uq_session_summaries_session_id recreate skipped — false positive; see upgrade. /Oliviercontribution)
    op.drop_index(op.f('ix_salesbook_engagement_logs_timestamp'), table_name='salesbook_engagement_logs')
    op.drop_index(op.f('ix_salesbook_engagement_logs_profile_id'), table_name='salesbook_engagement_logs')
    op.drop_index(op.f('ix_salesbook_engagement_logs_deal_id'), table_name='salesbook_engagement_logs')
    op.drop_table('salesbook_engagement_logs')
    op.drop_index(op.f('ix_salesbook_team_memberships_user_email'), table_name='salesbook_team_memberships')
    op.drop_index(op.f('ix_salesbook_team_memberships_profile_id'), table_name='salesbook_team_memberships')
    op.drop_table('salesbook_team_memberships')
    op.drop_index(op.f('ix_salesbook_pipeline_deals_profile_id'), table_name='salesbook_pipeline_deals')
    op.drop_table('salesbook_pipeline_deals')
    op.drop_index(op.f('ix_salesbook_onboarding_responses_question_key'), table_name='salesbook_onboarding_responses')
    op.drop_index(op.f('ix_salesbook_onboarding_responses_profile_id'), table_name='salesbook_onboarding_responses')
    op.drop_table('salesbook_onboarding_responses')
    op.drop_index(op.f('ix_salesbook_onboarding_progress_profile_id'), table_name='salesbook_onboarding_progress')
    op.drop_table('salesbook_onboarding_progress')
    op.drop_index(op.f('ix_salesbook_client_contact_extensions_profile_id'), table_name='salesbook_client_contact_extensions')
    op.drop_index(op.f('ix_salesbook_client_contact_extensions_primary_email'), table_name='salesbook_client_contact_extensions')
    op.drop_table('salesbook_client_contact_extensions')
    # ### end Alembic commands ###
