"""add salesbook moderation

Revision ID: 0008_add_salesbook_moderation
Revises: 0007_add_salesbook_tables
Create Date: 2026-04-26

/Oliviercontribution — adds rep-contribution moderation:
  - salesbook_comments: rep-authored opinions/notes against any salesbook target
    (status: pending | approved | rejected; admin reviews via the moderation route)
  - salesbook_pinned: admin's sticky picks (any approved entry can be pinned to top)
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008_add_salesbook_moderation'
down_revision = '0007_add_salesbook_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesbook_comments',
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('author_email', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_salesbook_comments_author_email'), 'salesbook_comments', ['author_email'], unique=False)
    op.create_index(op.f('ix_salesbook_comments_profile_id'), 'salesbook_comments', ['profile_id'], unique=False)
    op.create_index(op.f('ix_salesbook_comments_target_id'), 'salesbook_comments', ['target_id'], unique=False)
    op.create_table('salesbook_pinned',
    sa.Column('pin_id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('pinned_by', sa.String(length=255), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['company_profiles.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pin_id'),
    sa.UniqueConstraint('profile_id', 'target_type', 'target_id', name='uq_salesbook_pinned_target')
    )
    op.create_index(op.f('ix_salesbook_pinned_profile_id'), 'salesbook_pinned', ['profile_id'], unique=False)
    # NOTE: SQLite-vs-Postgres autogenerate false positive on uq_session_summaries — skipped. /Oliviercontribution
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # (uq_session_summaries recreate skipped — false positive; see upgrade. /Oliviercontribution)
    op.drop_index(op.f('ix_salesbook_pinned_profile_id'), table_name='salesbook_pinned')
    op.drop_table('salesbook_pinned')
    op.drop_index(op.f('ix_salesbook_comments_target_id'), table_name='salesbook_comments')
    op.drop_index(op.f('ix_salesbook_comments_profile_id'), table_name='salesbook_comments')
    op.drop_index(op.f('ix_salesbook_comments_author_email'), table_name='salesbook_comments')
    op.drop_table('salesbook_comments')
    # ### end Alembic commands ###
