"""Salesbook module public API. /Oliviercontribution."""

from hello_sales_backend.modules.salesbook.bootstrap import (
    SalesbookModule,
    build_salesbook_module,
)
from hello_sales_backend.modules.salesbook.permissions import (
    COMMENT_APPROVE_PERMISSION,
    COMMENT_WRITE_PERMISSION,
    ENGAGEMENT_READ_PERMISSION,
    ENGAGEMENT_WRITE_PERMISSION,
    ONBOARDING_READ_PERMISSION,
    ONBOARDING_WRITE_PERMISSION,
    PIN_READ_PERMISSION,
    PIN_WRITE_PERMISSION,
    PIPELINE_READ_PERMISSION,
    PIPELINE_WRITE_PERMISSION,
    SALESBOOK_READ_PERMISSION,
    TEAM_READ_PERMISSION,
    TEAM_WRITE_PERMISSION,
)
from hello_sales_backend.modules.salesbook.use_cases.salesbook_service import (
    SalesbookService,
)
from hello_sales_backend.modules.salesbook.use_cases.views import (
    ClientContactUpsertRequest,
    ClientContactView,
    EngagementLogCreateRequest,
    EngagementLogView,
    OnboardingBatchSubmit,
    OnboardingProgressView,
    OnboardingResponseSubmit,
    OnboardingResponseView,
    PipelineDealCreateRequest,
    PipelineDealUpdateRequest,
    PipelineDealView,
    SalesbookCommentApproveRequest,
    SalesbookCommentCreateRequest,
    SalesbookCommentView,
    SalesbookExhaustiveOnboardingEntry,
    SalesbookExhaustiveProductEntry,
    SalesbookExhaustiveView,
    SalesbookPinRequest,
    SalesbookPinView,
    TeamMembershipCreateRequest,
    TeamMembershipView,
)

__all__ = [
    "SalesbookModule",
    "SalesbookService",
    "build_salesbook_module",
    "ClientContactUpsertRequest",
    "ClientContactView",
    "EngagementLogCreateRequest",
    "EngagementLogView",
    "OnboardingBatchSubmit",
    "OnboardingProgressView",
    "OnboardingResponseSubmit",
    "OnboardingResponseView",
    "PipelineDealCreateRequest",
    "PipelineDealUpdateRequest",
    "PipelineDealView",
    "SalesbookCommentApproveRequest",
    "SalesbookCommentCreateRequest",
    "SalesbookCommentView",
    "SalesbookExhaustiveOnboardingEntry",
    "SalesbookExhaustiveProductEntry",
    "SalesbookExhaustiveView",
    "SalesbookPinRequest",
    "SalesbookPinView",
    "TeamMembershipCreateRequest",
    "TeamMembershipView",
    "SALESBOOK_READ_PERMISSION",
    "SALESBOOK_WRITE_PERMISSION",
    "ONBOARDING_READ_PERMISSION",
    "ONBOARDING_WRITE_PERMISSION",
    "PIPELINE_READ_PERMISSION",
    "PIPELINE_WRITE_PERMISSION",
    "ENGAGEMENT_READ_PERMISSION",
    "ENGAGEMENT_WRITE_PERMISSION",
    "TEAM_READ_PERMISSION",
    "TEAM_WRITE_PERMISSION",
    "COMMENT_WRITE_PERMISSION",
    "COMMENT_APPROVE_PERMISSION",
    "PIN_READ_PERMISSION",
    "PIN_WRITE_PERMISSION",
]
