"""Provider-neutral voice primitives."""

from hello_sales_backend.platform.voice.contracts import (
    AudioFormat,
    AudioInput,
    RealtimeVoiceProviderPort,
    SpeechChunk,
    SpeechChunkKind,
    SpeechSynthesisRequest,
    SpeechSynthesisResult,
    STTProviderPort,
    TranscriptEvent,
    TranscriptEventKind,
    TranscriptionRequest,
    TranscriptionResult,
    TTSProviderPort,
    TurnDetectionPort,
    TurnDetectionResult,
    VoiceCallContext,
    VoiceEvent,
    VoiceEventKind,
    VoiceSessionState,
    VoiceTransportMessage,
    VoiceTransportPort,
)

__all__ = [
    "AudioFormat",
    "AudioInput",
    "RealtimeVoiceProviderPort",
    "STTProviderPort",
    "SpeechChunk",
    "SpeechChunkKind",
    "SpeechSynthesisRequest",
    "SpeechSynthesisResult",
    "TTSProviderPort",
    "TranscriptEvent",
    "TranscriptEventKind",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TurnDetectionPort",
    "TurnDetectionResult",
    "VoiceCallContext",
    "VoiceEvent",
    "VoiceEventKind",
    "VoiceSessionState",
    "VoiceTransportMessage",
    "VoiceTransportPort",
]
